# configurations related to how data is processed when imported
[data_processing]
pre_split_filtering = false
demote_multis_to_singles = true

# configurations related to how data is filtered before analysis
[data_filtering]
min_ttvperiod = 0
min_snr = 12
